esphome:
  name: incubator

esp32:
  board: m5stick-c
  framework:
    type: arduino

<<: !include common.yaml

wifi:
  ssid: !secret wifi_ssid_outdoor
  password: !secret wifi_password
  ap:
    password: !secret fallback_ap_password

mqtt:
  broker: !secret mqtt_broker_host

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Strength"
    update_interval: 120s
    entity_category: "diagnostic"
  - platform: dht
    model: DHT22
    pin: GPIO9
    update_interval: 120s
    temperature:
        name: "Temperature"
    humidity:
        name: "Humidity"
