esphome:
  name: oiltank

esp32:
  board: m5stick-c
  framework:
    type: arduino

<<: !include common.yaml

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Strength"
    update_interval: 10s
    entity_category: "diagnostic"
  - platform: dht
    pin: GPIO12
    temperature:
        name: "Temperature"
    humidity:
        name: "Humidity"
  - platform: ultrasonic
    trigger_pin: GPIO10
    echo_pin: GPIO14
    name: "Fuel Level"
    timeout: 4m
    filters:
      # convert range from metres to percent level (2m = empty, 0m = full)
      - lambda: return round((2.0 - x) / 2.0 * 100);
    unit_of_measurement: "%"
    accuracy_decimals: 0
    update_interval: 20s
