esphome:
  name: oiltank

esp32:
  board: m5stick-c
  framework:
    type: arduino

<<: !include common.yaml

# oil tanks dimensions
# - height = 122cm
# - length = 182.5cm
# - width = 61cm
# - volume = 1358 litres

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Strength"
    update_interval: 10s
    entity_category: "diagnostic"
  - platform: dht
    pin: GPIO26
    update_interval: 10s
    temperature:
        name: "Temperature"
    humidity:
        name: "Humidity"
  - platform: ultrasonic
    trigger_pin: GPIO10
    echo_pin: GPIO14
    name: "Fuel Level"
    timeout: 4m
    filters:
      # convert range from metres to percent level (1.15m = empty, 0m = full)
      - lambda: return round((1.15 - x) / 1.15 * 100);
    unit_of_measurement: "%"
    accuracy_decimals: 0
    update_interval: 20s
