esphome:
  name: oiltank

esp32:
  board: m5stick-c
  framework:
    type: arduino

<<: !include common.yaml

wifi:
  ssid: !secret wifi_ssid_outdoor
  password: !secret wifi_password
  ap:
    password: !secret fallback_ap_password

mqtt:
  broker: !secret mqtt_broker_host
  username: !secret mqtt_username
  password: !secret mqtt_password

deep_sleep:
  id: sleep_timer
  run_duration: 10min   # process sensor readings for 10 minutes
  sleep_duration: 1h   # then sleep for an hour to save battery power

# oil tanks dimensions
# - height = 122cm
# - length = 182.5cm
# - width = 61cm
# - volume = 1358 litres

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Strength"
    update_interval: 120s
    entity_category: "diagnostic"
  - platform: dht
    pin: GPIO26
    update_interval: 120s
    temperature:
        name: "Temperature"
    humidity:
        name: "Humidity"
  - platform: ultrasonic
    id: level_sensor
    internal: true
    trigger_pin: GPIO10
    echo_pin: GPIO14
    timeout: 4m
    pulse_time: 30us
    update_interval: 10s
    filters:
      - max:
          window_size: 20
          send_every: 10
          send_first_at: 10
  - platform: template
    name: Fuel Level
    # convert from metres to percent level (1.15m = empty, 0m = full)
    lambda: return round((1.15 - id(level_sensor).state) / 1.15 * 100);
    unit_of_measurement: "%"
    accuracy_decimals: 0
    update_interval: 30s
  - platform: template
    name: Fuel Volume
    unit_of_measurement: "litres"
    accuracy_decimals: 0
    update_interval: 30s
    lambda: return (1.15 - id(level_sensor).state) * 1113.25;
