esphome:
  name: oiltank

esp32:
  board: m5stick-c
  framework:
    type: arduino

logger:

api:
  password: ""

ota:
  password: ""

mqtt:
  broker: !secret mqtt_broker_host

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: !secret fallback_ap_ssid
    password: !secret fallback_ap_password

captive_portal:

time:
  platform: homeassistant

sun:
  latitude: !secret home_lat
  longitude: !secret home_lon
  id: the_sun

sensor:
  - platform: dht
    pin: 9
    temperature:
        name: "Temperature"
    humidity:
        name: "Humidity"
  - platform: ultrasonic
    trigger_pin: 10
    echo_pin: 37
    name: "Level"
    # convert range from metres to level (2m = empty, 0m = full)
    filters:
      - lambda: return (2.0 - x) / 2.0 * 100;
    unit_of_measurement: "%"
    accuracy_decimals: 1
    update_interval: 20s

binary_sensor:
  - platform: template
    device_class: light
    name: "Daytime Indicator"
    publish_initial_state: true
    lambda: |-
      if (*id(the_sun).sunrise(5) > *id(the_sun).sunset(-5)) {
        return true;
      } else {
        return false;
      }

